// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"ddd/user/application"
	"ddd/user/domain"
	"ddd/user/domain/repository"
	"ddd/user/interfaces/controller"
)

// Injectors from wire.go:

func InitUserController() *controller.UserController {
	userRepository := repository.NewUserRepository()
	userService := domain.New(userRepository)
	userAppService := application.NewUserAppService(userService, userRepository)
	userController := controller.NewUserController(userAppService, userService, userRepository)
	return userController
}

